import socket
vna = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
vna.connect(("127.0.0.1", 5001))
vna.send(str.encode("*IDN?\n"))
reply=vna.recv(2056)
print (reply)
vna.send(str.encode("SENS:FREQ:STAR 1.6E9\n"))
#reply=vna.recv(2056)
#print (reply)
vna.send(str.encode("SENS:FREQ:STOP 2.4E9\n"))
#reply=vna.recv(2056)
#print (reply)
vna.send(str.encode("SENS:SWEEP:POINT 16001\n"))
vna.send(str.encode("SENS:BAND 70E1\n"))
vna.send(str.encode("CALCulate1:PARameter4:FORMat SMITh\n"))
vna.close()
print ("Comunicación terminada con exito")